[project]
name = "mcp-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub[mcp]>=0.32.0",
    "gradio[mcp]>=5.45.0",
]
